// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPoJy_daRjq21b71BtoDYPohU5xCLBWW8',
    appId: '1:1061245984719:web:ff06a4c4e332d213683cba',
    messagingSenderId: '1061245984719',
    projectId: 'auth-d693c',
    authDomain: 'auth-d693c.firebaseapp.com',
    storageBucket: 'auth-d693c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmaM9TjcVqbugpHjIId0jwuiEaT8mwqo',
    appId: '1:1061245984719:android:420380c29b202368683cba',
    messagingSenderId: '1061245984719',
    projectId: 'auth-d693c',
    storageBucket: 'auth-d693c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yKY7fi2sb8GAQRRxe_la2nhlQ3dgmF4',
    appId: '1:1061245984719:ios:d4e231feae8b9b60683cba',
    messagingSenderId: '1061245984719',
    projectId: 'auth-d693c',
    storageBucket: 'auth-d693c.appspot.com',
    iosClientId:
        '1061245984719-9o1nepgal7tdeqp7qc8p0mmj7o34dvd0.apps.googleusercontent.com',
    iosBundleId: 'auth.haitham.com.ecommerce',
  );
}
